version: "3.8"

services:
  blocklist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adguard-blocklist
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./data:/app/data:Z
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - CRON_SCHEDULE=0 0 * * *
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:mode=1777,size=64M
    networks:
      - blocklist_network

networks:
  blocklist_network:
    driver: bridge 